### ISSUE TITLE
Detectron2 to Caffe

### ISSUE THREAD

**Issue by ghost** [vanillapi/demonet#1]
@zhiqwang 
- Why did you include the `detectron2` tag in this repo
- Have you converted detectron2 instance segmentation into caffe or onnx

**Comment by zhiqwang** [comment]
Hi, @deepseek 
> * Why did you include the `detectron2` tag in this repo

I'm working in embedding `detectron2` to this repo.

> * Have you converted detectron2 instance segmentation into caffe or onnx

Now I can convert ssd model and its series from pytorch to caffe using [brocolli](https://github.com/inisis/brocolli), but the pytorch version of inisis's is 0.4.0, which is incompatible in most environment, I want to upgrade it to pytorch 1.3+ in this repo.

**Comment by ghost** [comment]
Thanks!
